// Fichier généré par generator/predict.py — ne pas éditer à la main.
window.PRONOSTICS_DATA = {
 "generatedAt": "2026-09-03 10:25 UTC",
 "demo": false,
 "leagues": [
  {
   "code": "FL1",
   "name": "Ligue 1"
  },
  {
   "code": "PL",
   "name": "Premier League"
  },
  {
   "code": "PD",
   "name": "Liga"
  },
  {
   "code": "SA",
   "name": "Serie A"
  },
  {
   "code": "BL1",
   "name": "Bundesliga"
  }
 ],
 "picks": [
  {
   "date": "2026-09-03",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Lille",
   "model": "poisson",
   "tip": "Victoire Lille",
   "confidence": 41,
   "odds": 2.44,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-03",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Lille",
   "model": "elo",
   "tip": "Victoire Lille",
   "confidence": 46,
   "odds": 2.19,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Auxerre",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 62,
   "odds": 1.6,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Auxerre",
   "model": "elo",
   "tip": "Victoire Olympique Lyon",
   "confidence": 64,
   "odds": 1.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "PSG — Monaco",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 71,
   "odds": 1.4,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "PSG — Monaco",
   "model": "elo",
   "tip": "Victoire PSG",
   "confidence": 58,
   "odds": 1.73,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Genoa — Como 1907",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 64,
   "odds": 1.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Genoa — Como 1907",
   "model": "elo",
   "tip": "Victoire Como 1907",
   "confidence": 63,
   "odds": 1.59,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — 1. FC Köln",
   "model": "poisson",
   "tip": "Victoire Stuttgart",
   "confidence": 67,
   "odds": 1.5,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-04",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — 1. FC Köln",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 71,
   "odds": 1.4,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — Lorient",
   "model": "poisson",
   "tip": "Victoire RC Lens",
   "confidence": 69,
   "odds": 1.45,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — Lorient",
   "model": "elo",
   "tip": "Victoire RC Lens",
   "confidence": 65,
   "odds": 1.55,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Brest",
   "model": "poisson",
   "tip": "Victoire Le Havre",
   "confidence": 39,
   "odds": 2.54,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Brest",
   "model": "elo",
   "tip": "Victoire Le Havre",
   "confidence": 44,
   "odds": 2.25,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Bournemouth",
   "model": "poisson",
   "tip": "Victoire Newcastle",
   "confidence": 44,
   "odds": 2.28,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Bournemouth",
   "model": "elo",
   "tip": "Victoire Bournemouth",
   "confidence": 37,
   "odds": 2.68,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Tottenham",
   "model": "poisson",
   "tip": "Victoire Nottingham",
   "confidence": 49,
   "odds": 2.02,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Tottenham",
   "model": "elo",
   "tip": "Victoire Nottingham",
   "confidence": 61,
   "odds": 1.65,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Leeds United",
   "model": "poisson",
   "tip": "Victoire Brighton Hove",
   "confidence": 53,
   "odds": 1.88,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Leeds United",
   "model": "elo",
   "tip": "Victoire Brighton Hove",
   "confidence": 44,
   "odds": 2.28,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Sunderland",
   "model": "poisson",
   "tip": "Victoire Brentford",
   "confidence": 50,
   "odds": 2.0,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Sunderland",
   "model": "elo",
   "tip": "Victoire Brentford",
   "confidence": 51,
   "odds": 1.97,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Crystal Palace",
   "model": "poisson",
   "tip": "Victoire Fulham",
   "confidence": 48,
   "odds": 2.08,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Crystal Palace",
   "model": "elo",
   "tip": "Victoire Fulham",
   "confidence": 51,
   "odds": 1.95,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Torino",
   "model": "poisson",
   "tip": "Victoire Fiorentina",
   "confidence": 42,
   "odds": 2.4,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Torino",
   "model": "elo",
   "tip": "Victoire Fiorentina",
   "confidence": 50,
   "odds": 1.98,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Inter — Napoli",
   "model": "poisson",
   "tip": "Victoire Inter",
   "confidence": 57,
   "odds": 1.75,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Inter — Napoli",
   "model": "elo",
   "tip": "Victoire Inter",
   "confidence": 65,
   "odds": 1.53,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Atalanta",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 49,
   "odds": 2.05,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Atalanta",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 57,
   "odds": 1.75,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — RB Leipzig",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 60,
   "odds": 1.67,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — RB Leipzig",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 61,
   "odds": 1.64,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Dortmund",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 49,
   "odds": 2.04,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Dortmund",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 46,
   "odds": 2.17,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — Union Berlin",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 67,
   "odds": 1.49,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — Union Berlin",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 63,
   "odds": 1.59,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Stade Rennais",
   "model": "poisson",
   "tip": "Victoire Stade Rennais",
   "confidence": 49,
   "odds": 2.04,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Stade Rennais",
   "model": "elo",
   "tip": "Victoire Stade Rennais",
   "confidence": 54,
   "odds": 1.84,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Paris FC",
   "model": "poisson",
   "tip": "Victoire Marseille",
   "confidence": 59,
   "odds": 1.71,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Paris FC",
   "model": "elo",
   "tip": "Victoire Marseille",
   "confidence": 45,
   "odds": 2.2,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Man United",
   "model": "poisson",
   "tip": "Victoire Man United",
   "confidence": 41,
   "odds": 2.44,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Man United",
   "model": "elo",
   "tip": "Victoire Man United",
   "confidence": 51,
   "odds": 1.98,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Arsenal — Chelsea",
   "model": "poisson",
   "tip": "Victoire Arsenal",
   "confidence": 71,
   "odds": 1.41,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Arsenal — Chelsea",
   "model": "elo",
   "tip": "Victoire Arsenal",
   "confidence": 73,
   "odds": 1.37,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Sassuolo",
   "model": "poisson",
   "tip": "Victoire Bologna",
   "confidence": 43,
   "odds": 2.35,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Sassuolo",
   "model": "elo",
   "tip": "Victoire Bologna",
   "confidence": 46,
   "odds": 2.15,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Milan",
   "model": "poisson",
   "tip": "Victoire Juventus",
   "confidence": 43,
   "odds": 2.33,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Milan",
   "model": "elo",
   "tip": "Victoire Juventus",
   "confidence": 52,
   "odds": 1.91,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Mainz",
   "model": "poisson",
   "tip": "Victoire HSV",
   "confidence": 38,
   "odds": 2.64,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Mainz",
   "model": "elo",
   "tip": "Victoire HSV",
   "confidence": 37,
   "odds": 2.73,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Augsburg",
   "model": "poisson",
   "tip": "Victoire Frankfurt",
   "confidence": 54,
   "odds": 1.85,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Augsburg",
   "model": "elo",
   "tip": "Victoire Frankfurt",
   "confidence": 37,
   "odds": 2.67,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-07",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cagliari — Lecce",
   "model": "poisson",
   "tip": "Victoire Cagliari",
   "confidence": 45,
   "odds": 2.21,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-07",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cagliari — Lecce",
   "model": "elo",
   "tip": "Victoire Cagliari",
   "confidence": 47,
   "odds": 2.11,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-07",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Lazio",
   "model": "poisson",
   "tip": "Victoire Lazio",
   "confidence": 36,
   "odds": 2.8,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-07",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Lazio",
   "model": "elo",
   "tip": "Victoire Udinese",
   "confidence": 38,
   "odds": 2.61,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-11",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Stade Rennais — Marseille",
   "model": "poisson",
   "tip": "Victoire Stade Rennais",
   "confidence": 41,
   "odds": 2.43,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-11",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Stade Rennais — Marseille",
   "model": "elo",
   "tip": "Victoire Stade Rennais",
   "confidence": 51,
   "odds": 1.97,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — Monaco",
   "model": "poisson",
   "tip": "Victoire Strasbourg",
   "confidence": 47,
   "odds": 2.11,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — Monaco",
   "model": "elo",
   "tip": "Victoire Strasbourg",
   "confidence": 39,
   "odds": 2.6,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lorient — Toulouse",
   "model": "poisson",
   "tip": "Victoire Lorient",
   "confidence": 43,
   "odds": 2.31,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lorient — Toulouse",
   "model": "elo",
   "tip": "Victoire Lorient",
   "confidence": 43,
   "odds": 2.35,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Nice",
   "model": "poisson",
   "tip": "Victoire Auxerre",
   "confidence": 49,
   "odds": 2.05,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Nice",
   "model": "elo",
   "tip": "Victoire Auxerre",
   "confidence": 52,
   "odds": 1.92,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Angers SCO",
   "model": "poisson",
   "tip": "Victoire Le Havre",
   "confidence": 42,
   "odds": 2.36,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Angers SCO",
   "model": "elo",
   "tip": "Victoire Le Havre",
   "confidence": 48,
   "odds": 2.07,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Olympique Lyon",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 39,
   "odds": 2.57,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Olympique Lyon",
   "model": "elo",
   "tip": "Victoire Paris FC",
   "confidence": 39,
   "odds": 2.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Fulham",
   "model": "poisson",
   "tip": "Victoire Liverpool",
   "confidence": 55,
   "odds": 1.83,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Fulham",
   "model": "elo",
   "tip": "Victoire Liverpool",
   "confidence": 56,
   "odds": 1.8,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Aston Villa — Nottingham",
   "model": "poisson",
   "tip": "Victoire Aston Villa",
   "confidence": 47,
   "odds": 2.11,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Aston Villa — Nottingham",
   "model": "elo",
   "tip": "Victoire Aston Villa",
   "confidence": 48,
   "odds": 2.1,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Brentford",
   "model": "poisson",
   "tip": "Victoire Bournemouth",
   "confidence": 44,
   "odds": 2.3,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Brentford",
   "model": "elo",
   "tip": "Victoire Bournemouth",
   "confidence": 51,
   "odds": 1.97,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Everton",
   "model": "poisson",
   "tip": "Victoire Everton",
   "confidence": 37,
   "odds": 2.73,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Everton",
   "model": "elo",
   "tip": "Victoire Everton",
   "confidence": 41,
   "odds": 2.46,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Arsenal",
   "model": "poisson",
   "tip": "Victoire Arsenal",
   "confidence": 59,
   "odds": 1.69,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Arsenal",
   "model": "elo",
   "tip": "Victoire Arsenal",
   "confidence": 61,
   "odds": 1.64,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — Milan",
   "model": "poisson",
   "tip": "Victoire Milan",
   "confidence": 42,
   "odds": 2.38,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — Milan",
   "model": "elo",
   "tip": "Victoire Lazio",
   "confidence": 39,
   "odds": 2.54,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Cagliari",
   "model": "poisson",
   "tip": "Victoire Atalanta",
   "confidence": 57,
   "odds": 1.75,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Cagliari",
   "model": "elo",
   "tip": "Victoire Atalanta",
   "confidence": 62,
   "odds": 1.62,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 44,
   "odds": 2.25,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Stuttgart",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 36,
   "odds": 2.77,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Augsburg — Leverkusen",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 51,
   "odds": 1.97,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Augsburg — Leverkusen",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 35,
   "odds": 2.88,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Frankfurt",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 42,
   "odds": 2.4,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Frankfurt",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 49,
   "odds": 2.06,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — M'gladbach",
   "model": "poisson",
   "tip": "Victoire Freiburg",
   "confidence": 52,
   "odds": 1.92,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — M'gladbach",
   "model": "elo",
   "tip": "Victoire Freiburg",
   "confidence": 52,
   "odds": 1.92,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Bremen",
   "model": "poisson",
   "tip": "Victoire 1. FC Köln",
   "confidence": 55,
   "odds": 1.82,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Bremen",
   "model": "elo",
   "tip": "Victoire 1. FC Köln",
   "confidence": 50,
   "odds": 2.0,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — PSG",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 66,
   "odds": 1.52,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — PSG",
   "model": "elo",
   "tip": "Victoire PSG",
   "confidence": 61,
   "odds": 1.63,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man United — Man City",
   "model": "poisson",
   "tip": "Victoire Man City",
   "confidence": 47,
   "odds": 2.11,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man United — Man City",
   "model": "elo",
   "tip": "Victoire Man United",
   "confidence": 34,
   "odds": 2.92,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Bologna",
   "model": "poisson",
   "tip": "Victoire Napoli",
   "confidence": 53,
   "odds": 1.89,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Bologna",
   "model": "elo",
   "tip": "Victoire Napoli",
   "confidence": 62,
   "odds": 1.6,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Sassuolo — Juventus",
   "model": "poisson",
   "tip": "Victoire Juventus",
   "confidence": 55,
   "odds": 1.8,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Sassuolo — Juventus",
   "model": "elo",
   "tip": "Victoire Juventus",
   "confidence": 51,
   "odds": 1.95,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — HSV",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 68,
   "odds": 1.48,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-13",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — HSV",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 66,
   "odds": 1.51,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Newcastle",
   "model": "poisson",
   "tip": "Victoire Leeds United",
   "confidence": 41,
   "odds": 2.44,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Newcastle",
   "model": "elo",
   "tip": "Victoire Leeds United",
   "confidence": 47,
   "odds": 2.11,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Como 1907 — Parma",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 71,
   "odds": 1.41,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Como 1907 — Parma",
   "model": "elo",
   "tip": "Victoire Como 1907",
   "confidence": 74,
   "odds": 1.34,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Roma",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 70,
   "odds": 1.43,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Roma",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 62,
   "odds": 1.61,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Inter — Udinese",
   "model": "poisson",
   "tip": "Victoire Inter",
   "confidence": 74,
   "odds": 1.35,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-14",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Inter — Udinese",
   "model": "elo",
   "tip": "Victoire Inter",
   "confidence": 75,
   "odds": 1.34,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Dortmund",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 67,
   "odds": 1.5,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Dortmund",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 64,
   "odds": 1.55,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Heidenheim — Mainz",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 41,
   "odds": 2.41,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Heidenheim — Mainz",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 38,
   "odds": 2.66,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — RB Leipzig",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 52,
   "odds": 1.91,
   "score": "4–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — RB Leipzig",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 48,
   "odds": 2.09,
   "score": "4–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Stuttgart",
   "confidence": 50,
   "odds": 2.0,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Stuttgart",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 51,
   "odds": 1.96,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "St. Pauli — Wolfsburg",
   "model": "poisson",
   "tip": "Victoire Wolfsburg",
   "confidence": 38,
   "odds": 2.66,
   "score": "1–3",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "St. Pauli — Wolfsburg",
   "model": "elo",
   "tip": "Victoire St. Pauli",
   "confidence": 42,
   "odds": 2.38,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Augsburg",
   "model": "poisson",
   "tip": "Victoire Union Berlin",
   "confidence": 39,
   "odds": 2.59,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Augsburg",
   "model": "elo",
   "tip": "Victoire Augsburg",
   "confidence": 41,
   "odds": 2.47,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Hoffenheim",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 53,
   "odds": 1.9,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Hoffenheim",
   "model": "elo",
   "tip": "Victoire Hoffenheim",
   "confidence": 48,
   "odds": 2.08,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — 1. FC Köln",
   "model": "poisson",
   "tip": "Victoire Bayern",
   "confidence": 91,
   "odds": 1.1,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — 1. FC Köln",
   "model": "elo",
   "tip": "Victoire Bayern",
   "confidence": 82,
   "odds": 1.22,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — HSV",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 67,
   "odds": 1.5,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — HSV",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 65,
   "odds": 1.55,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-21",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Strasbourg",
   "model": "poisson",
   "tip": "Victoire Marseille",
   "confidence": 52,
   "odds": 1.92,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-21",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Strasbourg",
   "model": "elo",
   "tip": "Victoire Marseille",
   "confidence": 44,
   "odds": 2.26,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — Auxerre",
   "model": "poisson",
   "tip": "Victoire RC Lens",
   "confidence": 70,
   "odds": 1.44,
   "score": "5–2",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — Auxerre",
   "model": "elo",
   "tip": "Victoire RC Lens",
   "confidence": 65,
   "odds": 1.53,
   "score": "5–2",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — Lorient",
   "model": "poisson",
   "tip": "Victoire Lorient",
   "confidence": 43,
   "odds": 2.34,
   "score": "0–0",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — Lorient",
   "model": "elo",
   "tip": "Victoire Lorient",
   "confidence": 41,
   "odds": 2.46,
   "score": "0–0",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Olympique Lyon",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 37,
   "odds": 2.69,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Olympique Lyon",
   "model": "elo",
   "tip": "Victoire Toulouse",
   "confidence": 35,
   "odds": 2.82,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Leeds United",
   "model": "poisson",
   "tip": "Victoire Nottingham",
   "confidence": 46,
   "odds": 2.16,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Leeds United",
   "model": "elo",
   "tip": "Victoire Nottingham",
   "confidence": 46,
   "odds": 2.19,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Crystal Palace",
   "model": "poisson",
   "tip": "Victoire Everton",
   "confidence": 47,
   "odds": 2.14,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Crystal Palace",
   "model": "elo",
   "tip": "Victoire Everton",
   "confidence": 47,
   "odds": 2.11,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Tottenham",
   "model": "poisson",
   "tip": "Victoire Brentford",
   "confidence": 53,
   "odds": 1.9,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Tottenham",
   "model": "elo",
   "tip": "Victoire Brentford",
   "confidence": 60,
   "odds": 1.67,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Como 1907",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 59,
   "odds": 1.7,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Como 1907",
   "model": "elo",
   "tip": "Victoire Como 1907",
   "confidence": 49,
   "odds": 2.05,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Genoa — Napoli",
   "model": "poisson",
   "tip": "Victoire Napoli",
   "confidence": 54,
   "odds": 1.85,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Genoa — Napoli",
   "model": "elo",
   "tip": "Victoire Napoli",
   "confidence": 52,
   "odds": 1.91,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Cagliari",
   "model": "poisson",
   "tip": "Victoire Cagliari",
   "confidence": 37,
   "odds": 2.72,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Cagliari",
   "model": "elo",
   "tip": "Victoire Parma",
   "confidence": 46,
   "odds": 2.19,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Lille",
   "model": "poisson",
   "tip": "Victoire Lille",
   "confidence": 51,
   "odds": 1.96,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Lille",
   "model": "elo",
   "tip": "Victoire Lille",
   "confidence": 58,
   "odds": 1.73,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Monaco",
   "model": "poisson",
   "tip": "Victoire Monaco",
   "confidence": 42,
   "odds": 2.36,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Havre — Monaco",
   "model": "elo",
   "tip": "Victoire Monaco",
   "confidence": 41,
   "odds": 2.45,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Stade Rennais — PSG",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 56,
   "odds": 1.78,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-23",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Stade Rennais — PSG",
   "model": "elo",
   "tip": "Victoire PSG",
   "confidence": 38,
   "odds": 2.62,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Bournemouth",
   "model": "poisson",
   "tip": "Victoire Man City",
   "confidence": 70,
   "odds": 1.44,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Bournemouth",
   "model": "elo",
   "tip": "Victoire Man City",
   "confidence": 58,
   "odds": 1.74,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Aston Villa",
   "model": "poisson",
   "tip": "Victoire Brighton Hove",
   "confidence": 44,
   "odds": 2.28,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Aston Villa",
   "model": "elo",
   "tip": "Victoire Brighton Hove",
   "confidence": 37,
   "odds": 2.69,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Liverpool",
   "model": "poisson",
   "tip": "Victoire Newcastle",
   "confidence": 39,
   "odds": 2.54,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-23",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Liverpool",
   "model": "elo",
   "tip": "Victoire Newcastle",
   "confidence": 34,
   "odds": 2.92,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Sassuolo",
   "model": "poisson",
   "tip": "Victoire Atalanta",
   "confidence": 52,
   "odds": 1.92,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Sassuolo",
   "model": "elo",
   "tip": "Victoire Atalanta",
   "confidence": 58,
   "odds": 1.72,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Milan",
   "model": "poisson",
   "tip": "Victoire Milan",
   "confidence": 58,
   "odds": 1.71,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-08-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Milan",
   "model": "elo",
   "tip": "Victoire Milan",
   "confidence": 42,
   "odds": 2.39,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-08-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Chelsea",
   "model": "poisson",
   "tip": "Victoire Fulham",
   "confidence": 39,
   "odds": 2.58,
   "score": "2–3",
   "status": "loss"
  },
  {
   "date": "2026-08-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Chelsea",
   "model": "elo",
   "tip": "Victoire Fulham",
   "confidence": 48,
   "odds": 2.07,
   "score": "2–3",
   "status": "loss"
  },
  {
   "date": "2026-08-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Lazio",
   "model": "poisson",
   "tip": "Victoire Bologna",
   "confidence": 39,
   "odds": 2.55,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-08-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Lazio",
   "model": "elo",
   "tip": "Victoire Bologna",
   "confidence": 42,
   "odds": 2.37,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-08-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Fiorentina",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 63,
   "odds": 1.58,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Fiorentina",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 63,
   "odds": 1.58,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-08-28",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lille — PSG",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 45,
   "odds": 2.23,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-28",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lille — PSG",
   "model": "elo",
   "tip": "Victoire Lille",
   "confidence": 35,
   "odds": 2.82,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-28",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Crystal Palace — Man City",
   "model": "poisson",
   "tip": "Victoire Man City",
   "confidence": 60,
   "odds": 1.65,
   "score": "1–4",
   "status": "win"
  },
  {
   "date": "2026-08-28",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Crystal Palace — Man City",
   "model": "elo",
   "tip": "Victoire Man City",
   "confidence": 65,
   "odds": 1.54,
   "score": "1–4",
   "status": "win"
  },
  {
   "date": "2026-08-28",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Bayern",
   "confidence": 79,
   "odds": 1.26,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-08-28",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Stuttgart",
   "model": "elo",
   "tip": "Victoire Bayern",
   "confidence": 68,
   "odds": 1.47,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — RC Lens",
   "model": "poisson",
   "tip": "Victoire RC Lens",
   "confidence": 48,
   "odds": 2.08,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — RC Lens",
   "model": "elo",
   "tip": "Victoire RC Lens",
   "confidence": 43,
   "odds": 2.35,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Le Havre",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 60,
   "odds": 1.66,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Le Havre",
   "model": "elo",
   "tip": "Victoire Olympique Lyon",
   "confidence": 66,
   "odds": 1.52,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Angers SCO",
   "model": "poisson",
   "tip": "Victoire Auxerre",
   "confidence": 46,
   "odds": 2.16,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Angers SCO",
   "model": "elo",
   "tip": "Victoire Auxerre",
   "confidence": 58,
   "odds": 1.74,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Toulouse",
   "model": "poisson",
   "tip": "Victoire Brest",
   "confidence": 38,
   "odds": 2.63,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Toulouse",
   "model": "elo",
   "tip": "Victoire Brest",
   "confidence": 35,
   "odds": 2.83,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Nottingham",
   "model": "poisson",
   "tip": "Victoire Liverpool",
   "confidence": 53,
   "odds": 1.87,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Nottingham",
   "model": "elo",
   "tip": "Victoire Liverpool",
   "confidence": 52,
   "odds": 1.94,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Everton",
   "model": "poisson",
   "tip": "Victoire Bournemouth",
   "confidence": 47,
   "odds": 2.13,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Everton",
   "model": "elo",
   "tip": "Victoire Bournemouth",
   "confidence": 60,
   "odds": 1.67,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Newcastle",
   "model": "poisson",
   "tip": "Victoire Tottenham",
   "confidence": 39,
   "odds": 2.57,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Newcastle",
   "model": "elo",
   "tip": "Victoire Newcastle",
   "confidence": 37,
   "odds": 2.73,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Sassuolo — Torino",
   "model": "poisson",
   "tip": "Victoire Sassuolo",
   "confidence": 50,
   "odds": 2.0,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Sassuolo — Torino",
   "model": "elo",
   "tip": "Victoire Sassuolo",
   "confidence": 48,
   "odds": 2.1,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Parma",
   "model": "poisson",
   "tip": "Victoire Juventus",
   "confidence": 66,
   "odds": 1.51,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Parma",
   "model": "elo",
   "tip": "Victoire Juventus",
   "confidence": 70,
   "odds": 1.43,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — M'gladbach",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 63,
   "odds": 1.59,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — M'gladbach",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 61,
   "odds": 1.65,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Frankfurt",
   "model": "poisson",
   "tip": "Victoire Frankfurt",
   "confidence": 39,
   "odds": 2.58,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Frankfurt",
   "model": "elo",
   "tip": "Victoire Union Berlin",
   "confidence": 41,
   "odds": 2.47,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Hoffenheim",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 48,
   "odds": 2.07,
   "score": "3–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Hoffenheim",
   "model": "elo",
   "tip": "Victoire Hoffenheim",
   "confidence": 52,
   "odds": 1.91,
   "score": "3–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Dortmund — HSV",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 73,
   "odds": 1.36,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Dortmund — HSV",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 72,
   "odds": 1.39,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Nice",
   "model": "poisson",
   "tip": "Victoire Paris FC",
   "confidence": 58,
   "odds": 1.73,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Nice",
   "model": "elo",
   "tip": "Victoire Paris FC",
   "confidence": 64,
   "odds": 1.57,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Monaco — Marseille",
   "model": "poisson",
   "tip": "Victoire Marseille",
   "confidence": 40,
   "odds": 2.48,
   "score": "2–0",
   "status": "loss"
  },
  {
   "date": "2026-08-30",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Monaco — Marseille",
   "model": "elo",
   "tip": "Victoire Monaco",
   "confidence": 42,
   "odds": 2.36,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Fulham",
   "model": "poisson",
   "tip": "Victoire Sunderland",
   "confidence": 41,
   "odds": 2.46,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Fulham",
   "model": "elo",
   "tip": "Victoire Sunderland",
   "confidence": 45,
   "odds": 2.22,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Chelsea — Brighton Hove",
   "model": "poisson",
   "tip": "Victoire Chelsea",
   "confidence": 42,
   "odds": 2.37,
   "score": "4–3",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Chelsea — Brighton Hove",
   "model": "elo",
   "tip": "Victoire Chelsea",
   "confidence": 37,
   "odds": 2.73,
   "score": "4–3",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Brentford",
   "model": "poisson",
   "tip": "Victoire Leeds United",
   "confidence": 37,
   "odds": 2.67,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-30",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Brentford",
   "model": "elo",
   "tip": "Victoire Leeds United",
   "confidence": 42,
   "odds": 2.4,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Como 1907",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 41,
   "odds": 2.46,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Como 1907",
   "model": "elo",
   "tip": "Victoire Napoli",
   "confidence": 41,
   "odds": 2.43,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — Genoa",
   "model": "poisson",
   "tip": "Victoire Lazio",
   "confidence": 46,
   "odds": 2.17,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — Genoa",
   "model": "elo",
   "tip": "Victoire Lazio",
   "confidence": 62,
   "odds": 1.61,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cagliari — Inter",
   "model": "poisson",
   "tip": "Victoire Inter",
   "confidence": 74,
   "odds": 1.35,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cagliari — Inter",
   "model": "elo",
   "tip": "Victoire Inter",
   "confidence": 67,
   "odds": 1.5,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — Bremen",
   "model": "poisson",
   "tip": "Victoire Freiburg",
   "confidence": 56,
   "odds": 1.78,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — Bremen",
   "model": "elo",
   "tip": "Victoire Freiburg",
   "confidence": 62,
   "odds": 1.61,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Aston Villa — Arsenal",
   "model": "poisson",
   "tip": "Victoire Arsenal",
   "confidence": 57,
   "odds": 1.74,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Aston Villa — Arsenal",
   "model": "elo",
   "tip": "Victoire Arsenal",
   "confidence": 55,
   "odds": 1.83,
   "score": "0–1",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lecce — Roma",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 64,
   "odds": 1.56,
   "score": "0–4",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lecce — Roma",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 55,
   "odds": 1.83,
   "score": "0–4",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Bologna",
   "model": "poisson",
   "tip": "Victoire Atalanta",
   "confidence": 48,
   "odds": 2.09,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-08-31",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Atalanta — Bologna",
   "model": "elo",
   "tip": "Victoire Atalanta",
   "confidence": 56,
   "odds": 1.8,
   "score": "1–0",
   "status": "win"
  }
 ]
};
