// Fichier généré par generator/predict.py — ne pas éditer à la main.
window.PRONOSTICS_DATA = {
 "generatedAt": "2026-07-28 08:16 UTC",
 "demo": false,
 "leagues": [
  {
   "code": "FL1",
   "name": "Ligue 1"
  },
  {
   "code": "PL",
   "name": "Premier League"
  },
  {
   "code": "PD",
   "name": "Liga"
  },
  {
   "code": "SA",
   "name": "Serie A"
  },
  {
   "code": "BL1",
   "name": "Bundesliga"
  }
 ],
 "picks": [
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Freiburg",
   "model": "poisson",
   "tip": "Victoire HSV",
   "confidence": 37,
   "odds": 2.71,
   "score": "3–2",
   "status": "win"
  },
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Freiburg",
   "model": "elo",
   "tip": "Victoire HSV",
   "confidence": 34,
   "odds": 2.92,
   "score": "3–2",
   "status": "win"
  },
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Heidenheim",
   "model": "poisson",
   "tip": "Victoire 1. FC Köln",
   "confidence": 61,
   "odds": 1.65,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Heidenheim",
   "model": "elo",
   "tip": "Victoire 1. FC Köln",
   "confidence": 52,
   "odds": 1.91,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Union Berlin",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 50,
   "odds": 2.01,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-10",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Union Berlin",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 62,
   "odds": 1.6,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Strasbourg",
   "model": "poisson",
   "tip": "Victoire Strasbourg",
   "confidence": 43,
   "odds": 2.32,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-05-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Strasbourg",
   "model": "elo",
   "tip": "Victoire Strasbourg",
   "confidence": 35,
   "odds": 2.86,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-05-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — PSG",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 39,
   "odds": 2.54,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-13",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "RC Lens — PSG",
   "model": "elo",
   "tip": "Victoire RC Lens",
   "confidence": 35,
   "odds": 2.82,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Dortmund",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 67,
   "odds": 1.5,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Dortmund",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 64,
   "odds": 1.55,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Heidenheim — Mainz",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 41,
   "odds": 2.41,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Heidenheim — Mainz",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 38,
   "odds": 2.66,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — RB Leipzig",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 52,
   "odds": 1.91,
   "score": "4–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — RB Leipzig",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 48,
   "odds": 2.09,
   "score": "4–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Stuttgart",
   "confidence": 50,
   "odds": 2.0,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Stuttgart",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 51,
   "odds": 1.96,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "St. Pauli — Wolfsburg",
   "model": "poisson",
   "tip": "Victoire Wolfsburg",
   "confidence": 38,
   "odds": 2.66,
   "score": "1–3",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "St. Pauli — Wolfsburg",
   "model": "elo",
   "tip": "Victoire St. Pauli",
   "confidence": 42,
   "odds": 2.38,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Augsburg",
   "model": "poisson",
   "tip": "Victoire Union Berlin",
   "confidence": 39,
   "odds": 2.59,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Augsburg",
   "model": "elo",
   "tip": "Victoire Augsburg",
   "confidence": 41,
   "odds": 2.47,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Hoffenheim",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 53,
   "odds": 1.9,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Hoffenheim",
   "model": "elo",
   "tip": "Victoire Hoffenheim",
   "confidence": 48,
   "odds": 2.08,
   "score": "4–0",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — 1. FC Köln",
   "model": "poisson",
   "tip": "Victoire Bayern",
   "confidence": 91,
   "odds": 1.1,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — 1. FC Köln",
   "model": "elo",
   "tip": "Victoire Bayern",
   "confidence": 82,
   "odds": 1.22,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — HSV",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 67,
   "odds": 1.5,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-16",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — HSV",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 65,
   "odds": 1.55,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lorient — Le Havre",
   "model": "poisson",
   "tip": "Victoire Lorient",
   "confidence": 54,
   "odds": 1.84,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lorient — Le Havre",
   "model": "elo",
   "tip": "Victoire Lorient",
   "confidence": 61,
   "odds": 1.64,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — PSG",
   "model": "poisson",
   "tip": "Victoire PSG",
   "confidence": 64,
   "odds": 1.57,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — PSG",
   "model": "elo",
   "tip": "Victoire PSG",
   "confidence": 54,
   "odds": 1.86,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — FC Metz",
   "model": "poisson",
   "tip": "Victoire Nice",
   "confidence": 60,
   "odds": 1.67,
   "score": "0–0",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — FC Metz",
   "model": "elo",
   "tip": "Victoire Nice",
   "confidence": 62,
   "odds": 1.6,
   "score": "0–0",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — RC Lens",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 39,
   "odds": 2.55,
   "score": "0–4",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — RC Lens",
   "model": "elo",
   "tip": "Victoire Olympique Lyon",
   "confidence": 43,
   "odds": 2.34,
   "score": "0–4",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Stade Rennais",
   "model": "poisson",
   "tip": "Victoire Marseille",
   "confidence": 52,
   "odds": 1.94,
   "score": "3–1",
   "status": "win"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — Stade Rennais",
   "model": "elo",
   "tip": "Victoire Stade Rennais",
   "confidence": 37,
   "odds": 2.69,
   "score": "3–1",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lille — Auxerre",
   "model": "poisson",
   "tip": "Victoire Lille",
   "confidence": 63,
   "odds": 1.6,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Lille — Auxerre",
   "model": "elo",
   "tip": "Victoire Lille",
   "confidence": 70,
   "odds": 1.42,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — Monaco",
   "model": "poisson",
   "tip": "Victoire Strasbourg",
   "confidence": 50,
   "odds": 2.01,
   "score": "5–4",
   "status": "win"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Strasbourg — Monaco",
   "model": "elo",
   "tip": "Victoire Strasbourg",
   "confidence": 39,
   "odds": 2.55,
   "score": "5–4",
   "status": "win"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Angers SCO",
   "model": "poisson",
   "tip": "Victoire Brest",
   "confidence": 51,
   "odds": 1.98,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-17",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Brest — Angers SCO",
   "model": "elo",
   "tip": "Victoire Brest",
   "confidence": 51,
   "odds": 1.96,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Atalanta",
   "model": "poisson",
   "tip": "Victoire Atalanta",
   "confidence": 49,
   "odds": 2.05,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-22",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Atalanta",
   "model": "elo",
   "tip": "Victoire Fiorentina",
   "confidence": 35,
   "odds": 2.89,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Alavés — Rayo Vallecano",
   "model": "poisson",
   "tip": "Victoire Alavés",
   "confidence": 40,
   "odds": 2.47,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Alavés — Rayo Vallecano",
   "model": "elo",
   "tip": "Victoire Alavés",
   "confidence": 36,
   "odds": 2.78,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Betis — Levante",
   "model": "poisson",
   "tip": "Victoire Real Betis",
   "confidence": 63,
   "odds": 1.58,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Betis — Levante",
   "model": "elo",
   "tip": "Victoire Real Betis",
   "confidence": 55,
   "odds": 1.8,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Sevilla FC",
   "model": "poisson",
   "tip": "Victoire Celta",
   "confidence": 59,
   "odds": 1.7,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Sevilla FC",
   "model": "elo",
   "tip": "Victoire Celta",
   "confidence": 53,
   "odds": 1.88,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Espanyol — Real Sociedad",
   "model": "poisson",
   "tip": "Victoire Espanyol",
   "confidence": 41,
   "odds": 2.41,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Espanyol — Real Sociedad",
   "model": "elo",
   "tip": "Victoire Espanyol",
   "confidence": 37,
   "odds": 2.67,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Osasuna",
   "model": "poisson",
   "tip": "Victoire Getafe",
   "confidence": 39,
   "odds": 2.59,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Osasuna",
   "model": "elo",
   "tip": "Victoire Getafe",
   "confidence": 52,
   "odds": 1.92,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Mallorca — Real Oviedo",
   "model": "poisson",
   "tip": "Victoire Mallorca",
   "confidence": 59,
   "odds": 1.69,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Mallorca — Real Oviedo",
   "model": "elo",
   "tip": "Victoire Mallorca",
   "confidence": 55,
   "odds": 1.81,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Madrid — Athletic",
   "model": "poisson",
   "tip": "Victoire Real Madrid",
   "confidence": 78,
   "odds": 1.27,
   "score": "4–2",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Madrid — Athletic",
   "model": "elo",
   "tip": "Victoire Real Madrid",
   "confidence": 75,
   "odds": 1.33,
   "score": "4–2",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Valencia — Barça",
   "model": "poisson",
   "tip": "Victoire Barça",
   "confidence": 69,
   "odds": 1.45,
   "score": "3–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Valencia — Barça",
   "model": "elo",
   "tip": "Victoire Barça",
   "confidence": 66,
   "odds": 1.52,
   "score": "3–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Girona — Elche",
   "model": "poisson",
   "tip": "Victoire Girona",
   "confidence": 41,
   "odds": 2.46,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Girona — Elche",
   "model": "elo",
   "tip": "Victoire Girona",
   "confidence": 42,
   "odds": 2.38,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Inter",
   "model": "poisson",
   "tip": "Victoire Inter",
   "confidence": 64,
   "odds": 1.56,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Inter",
   "model": "elo",
   "tip": "Victoire Inter",
   "confidence": 61,
   "odds": 1.63,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-05-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — AC Pisa",
   "model": "poisson",
   "tip": "Victoire Lazio",
   "confidence": 66,
   "odds": 1.52,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-05-23",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lazio — AC Pisa",
   "model": "elo",
   "tip": "Victoire Lazio",
   "confidence": 77,
   "odds": 1.3,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Chelsea",
   "model": "poisson",
   "tip": "Victoire Chelsea",
   "confidence": 38,
   "odds": 2.61,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Sunderland — Chelsea",
   "model": "elo",
   "tip": "Victoire Sunderland",
   "confidence": 44,
   "odds": 2.3,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Man United",
   "model": "poisson",
   "tip": "Victoire Brighton Hove",
   "confidence": 42,
   "odds": 2.38,
   "score": "0–3",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Man United",
   "model": "elo",
   "tip": "Victoire Man United",
   "confidence": 42,
   "odds": 2.39,
   "score": "0–3",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Crystal Palace — Arsenal",
   "model": "poisson",
   "tip": "Victoire Arsenal",
   "confidence": 61,
   "odds": 1.63,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Crystal Palace — Arsenal",
   "model": "elo",
   "tip": "Victoire Arsenal",
   "confidence": 63,
   "odds": 1.59,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Burnley — Wolverhampton",
   "model": "poisson",
   "tip": "Victoire Burnley",
   "confidence": 50,
   "odds": 2.01,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Burnley — Wolverhampton",
   "model": "elo",
   "tip": "Victoire Burnley",
   "confidence": 41,
   "odds": 2.46,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Newcastle",
   "model": "poisson",
   "tip": "Victoire Fulham",
   "confidence": 40,
   "odds": 2.51,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Newcastle",
   "model": "elo",
   "tip": "Victoire Fulham",
   "confidence": 41,
   "odds": 2.46,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Brentford",
   "model": "poisson",
   "tip": "Victoire Liverpool",
   "confidence": 50,
   "odds": 2.0,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Liverpool — Brentford",
   "model": "elo",
   "tip": "Victoire Liverpool",
   "confidence": 47,
   "odds": 2.11,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Aston Villa",
   "model": "poisson",
   "tip": "Victoire Man City",
   "confidence": 67,
   "odds": 1.49,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Aston Villa",
   "model": "elo",
   "tip": "Victoire Man City",
   "confidence": 70,
   "odds": 1.44,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Bournemouth",
   "model": "poisson",
   "tip": "Victoire Nottingham",
   "confidence": 40,
   "odds": 2.5,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Bournemouth",
   "model": "elo",
   "tip": "Victoire Bournemouth",
   "confidence": 38,
   "odds": 2.63,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Everton",
   "model": "poisson",
   "tip": "Victoire Tottenham",
   "confidence": 39,
   "odds": 2.58,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Everton",
   "model": "elo",
   "tip": "Victoire Everton",
   "confidence": 38,
   "odds": 2.66,
   "score": "1–0",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "West Ham — Leeds United",
   "model": "poisson",
   "tip": "Victoire Leeds United",
   "confidence": 41,
   "odds": 2.42,
   "score": "3–0",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "West Ham — Leeds United",
   "model": "elo",
   "tip": "Victoire Leeds United",
   "confidence": 41,
   "odds": 2.46,
   "score": "3–0",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Atleti",
   "model": "poisson",
   "tip": "Victoire Villarreal",
   "confidence": 47,
   "odds": 2.13,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Atleti",
   "model": "elo",
   "tip": "Victoire Villarreal",
   "confidence": 42,
   "odds": 2.37,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Sassuolo",
   "model": "poisson",
   "tip": "Victoire Sassuolo",
   "confidence": 44,
   "odds": 2.25,
   "score": "1–0",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Sassuolo",
   "model": "elo",
   "tip": "Victoire Parma",
   "confidence": 38,
   "odds": 2.67,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Udinese",
   "model": "poisson",
   "tip": "Victoire Napoli",
   "confidence": 56,
   "odds": 1.79,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Napoli — Udinese",
   "model": "elo",
   "tip": "Victoire Napoli",
   "confidence": 59,
   "odds": 1.7,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Milan — Cagliari",
   "model": "poisson",
   "tip": "Victoire Milan",
   "confidence": 62,
   "odds": 1.62,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Milan — Cagliari",
   "model": "elo",
   "tip": "Victoire Milan",
   "confidence": 67,
   "odds": 1.5,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Verona — Roma",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 72,
   "odds": 1.4,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Verona — Roma",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 71,
   "odds": 1.4,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cremonese — Como 1907",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 69,
   "odds": 1.46,
   "score": "1–4",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Cremonese — Como 1907",
   "model": "elo",
   "tip": "Victoire Como 1907",
   "confidence": 64,
   "odds": 1.57,
   "score": "1–4",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lecce — Genoa",
   "model": "poisson",
   "tip": "Victoire Genoa",
   "confidence": 43,
   "odds": 2.32,
   "score": "1–0",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Lecce — Genoa",
   "model": "elo",
   "tip": "Victoire Lecce",
   "confidence": 37,
   "odds": 2.7,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Juventus",
   "model": "poisson",
   "tip": "Victoire Juventus",
   "confidence": 65,
   "odds": 1.53,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-05-24",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Torino — Juventus",
   "model": "elo",
   "tip": "Victoire Juventus",
   "confidence": 52,
   "odds": 1.92,
   "score": "2–2",
   "status": "loss"
  }
 ]
};
