// Fichier généré par generator/predict.py — ne pas éditer à la main.
window.PRONOSTICS_DATA = {
 "generatedAt": "2026-09-16 10:31 UTC",
 "demo": false,
 "leagues": [
  {
   "code": "FL1",
   "name": "Ligue 1"
  },
  {
   "code": "PL",
   "name": "Premier League"
  },
  {
   "code": "PD",
   "name": "Liga"
  },
  {
   "code": "SA",
   "name": "Serie A"
  },
  {
   "code": "BL1",
   "name": "Bundesliga"
  }
 ],
 "picks": [
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Deportivo — Sevilla FC",
   "model": "poisson",
   "tip": "Victoire Deportivo",
   "confidence": 47,
   "odds": 2.13,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Deportivo — Sevilla FC",
   "model": "elo",
   "tip": "Victoire Deportivo",
   "confidence": 46,
   "odds": 2.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Atleti — Osasuna",
   "model": "poisson",
   "tip": "Victoire Atleti",
   "confidence": 74,
   "odds": 1.36,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Atleti — Osasuna",
   "model": "elo",
   "tip": "Victoire Atleti",
   "confidence": 53,
   "odds": 1.87,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Levante — Athletic",
   "model": "poisson",
   "tip": "Victoire Athletic",
   "confidence": 44,
   "odds": 2.26,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Levante — Athletic",
   "model": "elo",
   "tip": "Victoire Levante",
   "confidence": 41,
   "odds": 2.46,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Barça — Santander",
   "model": "poisson",
   "tip": "Victoire Barça",
   "confidence": 96,
   "odds": 1.05,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-16",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Barça — Santander",
   "model": "elo",
   "tip": "Victoire Barça",
   "confidence": 60,
   "odds": 1.65,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-17",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Betis — Getafe",
   "model": "poisson",
   "tip": "Victoire Real Betis",
   "confidence": 56,
   "odds": 1.77,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-17",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Betis — Getafe",
   "model": "elo",
   "tip": "Victoire Real Betis",
   "confidence": 54,
   "odds": 1.85,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-17",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Málaga — Villarreal",
   "model": "poisson",
   "tip": "Victoire Villarreal",
   "confidence": 56,
   "odds": 1.79,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-17",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Málaga — Villarreal",
   "model": "elo",
   "tip": "Victoire Málaga",
   "confidence": 46,
   "odds": 2.19,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Monaco — RC Lens",
   "model": "poisson",
   "tip": "Victoire Monaco",
   "confidence": 66,
   "odds": 1.52,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Monaco — RC Lens",
   "model": "elo",
   "tip": "Victoire Monaco",
   "confidence": 55,
   "odds": 1.81,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Chelsea",
   "model": "poisson",
   "tip": "Victoire Brentford",
   "confidence": 62,
   "odds": 1.62,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brentford — Chelsea",
   "model": "elo",
   "tip": "Victoire Brentford",
   "confidence": 44,
   "odds": 2.26,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Espanyol — Elche",
   "model": "poisson",
   "tip": "Victoire Espanyol",
   "confidence": 78,
   "odds": 1.29,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Espanyol — Elche",
   "model": "elo",
   "tip": "Victoire Espanyol",
   "confidence": 54,
   "odds": 1.84,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Monza — Sassuolo",
   "model": "poisson",
   "tip": "Victoire Sassuolo",
   "confidence": 74,
   "odds": 1.35,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Monza — Sassuolo",
   "model": "elo",
   "tip": "Victoire Sassuolo",
   "confidence": 35,
   "odds": 2.85,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Union Berlin",
   "model": "poisson",
   "tip": "Victoire Bayern",
   "confidence": 93,
   "odds": 1.08,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-18",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Union Berlin",
   "model": "elo",
   "tip": "Victoire Bayern",
   "confidence": 82,
   "odds": 1.22,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Strasbourg",
   "model": "poisson",
   "tip": "Victoire Paris FC",
   "confidence": 69,
   "odds": 1.45,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Paris FC — Strasbourg",
   "model": "elo",
   "tip": "Victoire Paris FC",
   "confidence": 46,
   "odds": 2.17,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Mans — Lorient",
   "model": "poisson",
   "tip": "Victoire Lorient",
   "confidence": 41,
   "odds": 2.45,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Le Mans — Lorient",
   "model": "elo",
   "tip": "Victoire Le Mans",
   "confidence": 41,
   "odds": 2.41,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Le Havre",
   "model": "poisson",
   "tip": "Match nul",
   "confidence": 39,
   "odds": 2.58,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Toulouse — Le Havre",
   "model": "elo",
   "tip": "Victoire Toulouse",
   "confidence": 44,
   "odds": 2.27,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Troyes",
   "model": "poisson",
   "tip": "Victoire Angers SCO",
   "confidence": 55,
   "odds": 1.81,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Angers SCO — Troyes",
   "model": "elo",
   "tip": "Victoire Angers SCO",
   "confidence": 46,
   "odds": 2.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Stade Rennais",
   "model": "poisson",
   "tip": "Victoire Olympique Lyon",
   "confidence": 53,
   "odds": 1.9,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Olympique Lyon — Stade Rennais",
   "model": "elo",
   "tip": "Victoire Olympique Lyon",
   "confidence": 43,
   "odds": 2.33,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Aston Villa",
   "model": "poisson",
   "tip": "Match nul",
   "confidence": 78,
   "odds": 1.29,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Tottenham — Aston Villa",
   "model": "elo",
   "tip": "Victoire Tottenham",
   "confidence": 46,
   "odds": 2.16,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Ipswich Town",
   "model": "poisson",
   "tip": "Victoire Everton",
   "confidence": 69,
   "odds": 1.46,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Everton — Ipswich Town",
   "model": "elo",
   "tip": "Victoire Everton",
   "confidence": 49,
   "odds": 2.06,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Arsenal",
   "model": "poisson",
   "tip": "Victoire Arsenal",
   "confidence": 64,
   "odds": 1.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Brighton Hove — Arsenal",
   "model": "elo",
   "tip": "Victoire Brighton Hove",
   "confidence": 38,
   "odds": 2.66,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Hull City",
   "model": "poisson",
   "tip": "Victoire Hull City",
   "confidence": 63,
   "odds": 1.59,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Newcastle — Hull City",
   "model": "elo",
   "tip": "Victoire Newcastle",
   "confidence": 38,
   "odds": 2.6,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Coventry City",
   "model": "poisson",
   "tip": "Victoire Nottingham",
   "confidence": 82,
   "odds": 1.22,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Nottingham — Coventry City",
   "model": "elo",
   "tip": "Victoire Nottingham",
   "confidence": 56,
   "odds": 1.79,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Osasuna — Rayo Vallecano",
   "model": "poisson",
   "tip": "Victoire Osasuna",
   "confidence": 43,
   "odds": 2.32,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Osasuna — Rayo Vallecano",
   "model": "elo",
   "tip": "Victoire Osasuna",
   "confidence": 44,
   "odds": 2.27,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Athletic — Alavés",
   "model": "poisson",
   "tip": "Victoire Alavés",
   "confidence": 44,
   "odds": 2.28,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Athletic — Alavés",
   "model": "elo",
   "tip": "Victoire Athletic",
   "confidence": 43,
   "odds": 2.3,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Santander",
   "model": "poisson",
   "tip": "Victoire Santander",
   "confidence": 46,
   "odds": 2.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Santander",
   "model": "elo",
   "tip": "Victoire Celta",
   "confidence": 37,
   "odds": 2.67,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Sevilla FC — Barça",
   "model": "poisson",
   "tip": "Victoire Barça",
   "confidence": 79,
   "odds": 1.26,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Sevilla FC — Barça",
   "model": "elo",
   "tip": "Victoire Barça",
   "confidence": 38,
   "odds": 2.63,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Torino",
   "model": "poisson",
   "tip": "Victoire Torino",
   "confidence": 40,
   "odds": 2.52,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Bologna — Torino",
   "model": "elo",
   "tip": "Victoire Bologna",
   "confidence": 42,
   "odds": 2.37,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Cagliari",
   "model": "poisson",
   "tip": "Victoire Cagliari",
   "confidence": 63,
   "odds": 1.59,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Udinese — Cagliari",
   "model": "elo",
   "tip": "Victoire Udinese",
   "confidence": 36,
   "odds": 2.8,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Inter",
   "model": "poisson",
   "tip": "Victoire Roma",
   "confidence": 85,
   "odds": 1.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Roma — Inter",
   "model": "elo",
   "tip": "Victoire Roma",
   "confidence": 47,
   "odds": 2.12,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Venezia FC — Lazio",
   "model": "poisson",
   "tip": "Victoire Lazio",
   "confidence": 85,
   "odds": 1.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Venezia FC — Lazio",
   "model": "elo",
   "tip": "Victoire Lazio",
   "confidence": 45,
   "odds": 2.22,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — 1. FC Köln",
   "model": "poisson",
   "tip": "Victoire 1. FC Köln",
   "confidence": 38,
   "odds": 2.64,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — 1. FC Köln",
   "model": "elo",
   "tip": "Victoire HSV",
   "confidence": 45,
   "odds": 2.2,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Mainz",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 38,
   "odds": 2.67,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "M'gladbach — Mainz",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 34,
   "odds": 2.93,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Augsburg",
   "model": "poisson",
   "tip": "Victoire Augsburg",
   "confidence": 39,
   "odds": 2.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — Augsburg",
   "model": "elo",
   "tip": "Victoire Augsburg",
   "confidence": 45,
   "odds": 2.22,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Freiburg",
   "model": "poisson",
   "tip": "Victoire Frankfurt",
   "confidence": 43,
   "odds": 2.32,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Freiburg",
   "model": "elo",
   "tip": "Victoire Freiburg",
   "confidence": 38,
   "odds": 2.62,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — Dortmund",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 47,
   "odds": 2.14,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-19",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — Dortmund",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 40,
   "odds": 2.53,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Brest",
   "model": "poisson",
   "tip": "Victoire Brest",
   "confidence": 70,
   "odds": 1.43,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Auxerre — Brest",
   "model": "elo",
   "tip": "Victoire Auxerre",
   "confidence": 37,
   "odds": 2.67,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — Lille",
   "model": "poisson",
   "tip": "Victoire Lille",
   "confidence": 76,
   "odds": 1.31,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Nice — Lille",
   "model": "elo",
   "tip": "Victoire Lille",
   "confidence": 40,
   "odds": 2.53,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — PSG",
   "model": "poisson",
   "tip": "Victoire Marseille",
   "confidence": 39,
   "odds": 2.56,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "FL1",
   "leagueName": "Ligue 1",
   "match": "Marseille — PSG",
   "model": "elo",
   "tip": "Victoire Marseille",
   "confidence": 38,
   "odds": 2.6,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Liverpool",
   "model": "poisson",
   "tip": "Victoire Liverpool",
   "confidence": 53,
   "odds": 1.87,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Bournemouth — Liverpool",
   "model": "elo",
   "tip": "Victoire Bournemouth",
   "confidence": 39,
   "odds": 2.59,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Crystal Palace",
   "model": "poisson",
   "tip": "Victoire Leeds United",
   "confidence": 87,
   "odds": 1.15,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Leeds United — Crystal Palace",
   "model": "elo",
   "tip": "Victoire Leeds United",
   "confidence": 57,
   "odds": 1.76,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Sunderland",
   "model": "poisson",
   "tip": "Victoire Man City",
   "confidence": 76,
   "odds": 1.31,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Man City — Sunderland",
   "model": "elo",
   "tip": "Victoire Man City",
   "confidence": 58,
   "odds": 1.74,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Man United",
   "model": "poisson",
   "tip": "Victoire Man United",
   "confidence": 56,
   "odds": 1.79,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PL",
   "leagueName": "Premier League",
   "match": "Fulham — Man United",
   "model": "elo",
   "tip": "Victoire Fulham",
   "confidence": 38,
   "odds": 2.66,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Málaga",
   "model": "poisson",
   "tip": "Match nul",
   "confidence": 45,
   "odds": 2.23,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Málaga",
   "model": "elo",
   "tip": "Victoire Getafe",
   "confidence": 46,
   "odds": 2.15,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Atleti — Real Madrid",
   "model": "poisson",
   "tip": "Victoire Real Madrid",
   "confidence": 52,
   "odds": 1.94,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Atleti — Real Madrid",
   "model": "elo",
   "tip": "Victoire Atleti",
   "confidence": 40,
   "odds": 2.51,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Deportivo — Real Betis",
   "model": "poisson",
   "tip": "Victoire Deportivo",
   "confidence": 50,
   "odds": 1.98,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Deportivo — Real Betis",
   "model": "elo",
   "tip": "Victoire Deportivo",
   "confidence": 43,
   "odds": 2.35,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Levante",
   "model": "poisson",
   "tip": "Victoire Villarreal",
   "confidence": 42,
   "odds": 2.39,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Levante",
   "model": "elo",
   "tip": "Victoire Villarreal",
   "confidence": 39,
   "odds": 2.58,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Valencia — Real Sociedad",
   "model": "poisson",
   "tip": "Victoire Real Sociedad",
   "confidence": 49,
   "odds": 2.04,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Valencia — Real Sociedad",
   "model": "elo",
   "tip": "Victoire Valencia",
   "confidence": 41,
   "odds": 2.47,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Napoli",
   "model": "poisson",
   "tip": "Victoire Napoli",
   "confidence": 74,
   "odds": 1.34,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Fiorentina — Napoli",
   "model": "elo",
   "tip": "Victoire Fiorentina",
   "confidence": 36,
   "odds": 2.76,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Frosinone — Como 1907",
   "model": "poisson",
   "tip": "Victoire Como 1907",
   "confidence": 46,
   "odds": 2.16,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Frosinone — Como 1907",
   "model": "elo",
   "tip": "Victoire Frosinone",
   "confidence": 38,
   "odds": 2.65,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Genoa",
   "model": "poisson",
   "tip": "Match nul",
   "confidence": 43,
   "odds": 2.34,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Parma — Genoa",
   "model": "elo",
   "tip": "Victoire Parma",
   "confidence": 46,
   "odds": 2.17,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Atalanta",
   "model": "poisson",
   "tip": "Victoire Juventus",
   "confidence": 44,
   "odds": 2.25,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Juventus — Atalanta",
   "model": "elo",
   "tip": "Victoire Juventus",
   "confidence": 48,
   "odds": 2.09,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Milan — Lecce",
   "model": "poisson",
   "tip": "Victoire Milan",
   "confidence": 64,
   "odds": 1.57,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "SA",
   "leagueName": "Serie A",
   "match": "Milan — Lecce",
   "model": "elo",
   "tip": "Victoire Milan",
   "confidence": 51,
   "odds": 1.95,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — RB Leipzig",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 46,
   "odds": 2.18,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-09-20",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — RB Leipzig",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 44,
   "odds": 2.3,
   "score": null,
   "status": "pending"
  },
  {
   "date": "2026-08-28",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Bayern",
   "confidence": 79,
   "odds": 1.26,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-08-28",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bayern — Stuttgart",
   "model": "elo",
   "tip": "Victoire Bayern",
   "confidence": 68,
   "odds": 1.47,
   "score": "5–1",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — M'gladbach",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 63,
   "odds": 1.59,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — M'gladbach",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 61,
   "odds": 1.65,
   "score": "3–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Frankfurt",
   "model": "poisson",
   "tip": "Victoire Frankfurt",
   "confidence": 39,
   "odds": 2.58,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Union Berlin — Frankfurt",
   "model": "elo",
   "tip": "Victoire Union Berlin",
   "confidence": 41,
   "odds": 2.47,
   "score": "3–3",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Hoffenheim",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 48,
   "odds": 2.07,
   "score": "3–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Hoffenheim",
   "model": "elo",
   "tip": "Victoire Hoffenheim",
   "confidence": 52,
   "odds": 1.91,
   "score": "3–2",
   "status": "loss"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Dortmund — HSV",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 73,
   "odds": 1.36,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-29",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Dortmund — HSV",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 72,
   "odds": 1.39,
   "score": "2–0",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — Bremen",
   "model": "poisson",
   "tip": "Victoire Freiburg",
   "confidence": 56,
   "odds": 1.78,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-08-30",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — Bremen",
   "model": "elo",
   "tip": "Victoire Freiburg",
   "confidence": 62,
   "odds": 1.61,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-09-04",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — 1. FC Köln",
   "model": "poisson",
   "tip": "Victoire Stuttgart",
   "confidence": 67,
   "odds": 1.5,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-09-04",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Stuttgart — 1. FC Köln",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 71,
   "odds": 1.4,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — RB Leipzig",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 60,
   "odds": 1.67,
   "score": "3–1",
   "status": "loss"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Bremen — RB Leipzig",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 61,
   "odds": 1.64,
   "score": "3–1",
   "status": "loss"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Dortmund",
   "model": "poisson",
   "tip": "Victoire Dortmund",
   "confidence": 49,
   "odds": 2.05,
   "score": "2–3",
   "status": "win"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Dortmund",
   "model": "elo",
   "tip": "Victoire Dortmund",
   "confidence": 46,
   "odds": 2.17,
   "score": "2–3",
   "status": "win"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — Union Berlin",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 67,
   "odds": 1.49,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-09-05",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Leverkusen — Union Berlin",
   "model": "elo",
   "tip": "Victoire Leverkusen",
   "confidence": 63,
   "odds": 1.59,
   "score": "4–0",
   "status": "win"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Mainz",
   "model": "poisson",
   "tip": "Victoire HSV",
   "confidence": 38,
   "odds": 2.63,
   "score": "0–5",
   "status": "loss"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "HSV — Mainz",
   "model": "elo",
   "tip": "Victoire HSV",
   "confidence": 37,
   "odds": 2.73,
   "score": "0–5",
   "status": "loss"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Augsburg",
   "model": "poisson",
   "tip": "Victoire Frankfurt",
   "confidence": 54,
   "odds": 1.86,
   "score": "1–4",
   "status": "loss"
  },
  {
   "date": "2026-09-06",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Frankfurt — Augsburg",
   "model": "elo",
   "tip": "Victoire Frankfurt",
   "confidence": 37,
   "odds": 2.67,
   "score": "1–4",
   "status": "loss"
  },
  {
   "date": "2026-09-11",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Sevilla FC — Valencia",
   "model": "poisson",
   "tip": "Victoire Sevilla FC",
   "confidence": 92,
   "odds": 1.09,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-09-11",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Sevilla FC — Valencia",
   "model": "elo",
   "tip": "Victoire Sevilla FC",
   "confidence": 56,
   "odds": 1.8,
   "score": "1–0",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Santander — Alavés",
   "model": "poisson",
   "tip": "Victoire Alavés",
   "confidence": 75,
   "odds": 1.34,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Santander — Alavés",
   "model": "elo",
   "tip": "Victoire Alavés",
   "confidence": 36,
   "odds": 2.78,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Osasuna — Espanyol",
   "model": "poisson",
   "tip": "Victoire Espanyol",
   "confidence": 37,
   "odds": 2.67,
   "score": "0–2",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Osasuna — Espanyol",
   "model": "elo",
   "tip": "Victoire Osasuna",
   "confidence": 49,
   "odds": 2.06,
   "score": "0–2",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Athletic — Elche",
   "model": "poisson",
   "tip": "Victoire Athletic",
   "confidence": 85,
   "odds": 1.18,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Athletic — Elche",
   "model": "elo",
   "tip": "Victoire Athletic",
   "confidence": 56,
   "odds": 1.8,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Madrid — Rayo Vallecano",
   "model": "poisson",
   "tip": "Victoire Real Madrid",
   "confidence": 95,
   "odds": 1.06,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Madrid — Rayo Vallecano",
   "model": "elo",
   "tip": "Victoire Real Madrid",
   "confidence": 53,
   "odds": 1.9,
   "score": "4–1",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Stuttgart",
   "model": "poisson",
   "tip": "Victoire Hoffenheim",
   "confidence": 42,
   "odds": 2.4,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Hoffenheim — Stuttgart",
   "model": "elo",
   "tip": "Victoire Stuttgart",
   "confidence": 40,
   "odds": 2.51,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Augsburg — Leverkusen",
   "model": "poisson",
   "tip": "Victoire Leverkusen",
   "confidence": 51,
   "odds": 1.97,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Augsburg — Leverkusen",
   "model": "elo",
   "tip": "Victoire Augsburg",
   "confidence": 35,
   "odds": 2.83,
   "score": "2–2",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Frankfurt",
   "model": "poisson",
   "tip": "Victoire Mainz",
   "confidence": 47,
   "odds": 2.13,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Mainz — Frankfurt",
   "model": "elo",
   "tip": "Victoire Mainz",
   "confidence": 57,
   "odds": 1.76,
   "score": "1–3",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — M'gladbach",
   "model": "poisson",
   "tip": "Victoire Freiburg",
   "confidence": 53,
   "odds": 1.9,
   "score": "5–0",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "Freiburg — M'gladbach",
   "model": "elo",
   "tip": "Victoire Freiburg",
   "confidence": 58,
   "odds": 1.74,
   "score": "5–0",
   "status": "win"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Bremen",
   "model": "poisson",
   "tip": "Victoire 1. FC Köln",
   "confidence": 52,
   "odds": 1.94,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-12",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "1. FC Köln — Bremen",
   "model": "elo",
   "tip": "Victoire 1. FC Köln",
   "confidence": 44,
   "odds": 2.28,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Málaga",
   "model": "poisson",
   "tip": "Match nul",
   "confidence": 54,
   "odds": 1.85,
   "score": "1–1",
   "status": "win"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Celta — Málaga",
   "model": "elo",
   "tip": "Victoire Celta",
   "confidence": 44,
   "odds": 2.29,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Levante — Barça",
   "model": "poisson",
   "tip": "Victoire Barça",
   "confidence": 87,
   "odds": 1.15,
   "score": "2–4",
   "status": "win"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Levante — Barça",
   "model": "elo",
   "tip": "Victoire Barça",
   "confidence": 38,
   "odds": 2.66,
   "score": "2–4",
   "status": "win"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Deportivo",
   "model": "poisson",
   "tip": "Victoire Deportivo",
   "confidence": 61,
   "odds": 1.64,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Getafe — Deportivo",
   "model": "elo",
   "tip": "Victoire Getafe",
   "confidence": 35,
   "odds": 2.86,
   "score": "1–1",
   "status": "loss"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Sociedad — Atleti",
   "model": "poisson",
   "tip": "Victoire Atleti",
   "confidence": 43,
   "odds": 2.3,
   "score": "0–3",
   "status": "win"
  },
  {
   "date": "2026-09-13",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Real Sociedad — Atleti",
   "model": "elo",
   "tip": "Victoire Real Sociedad",
   "confidence": 41,
   "odds": 2.43,
   "score": "0–3",
   "status": "loss"
  },
  {
   "date": "2026-09-13",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — HSV",
   "model": "poisson",
   "tip": "Victoire RB Leipzig",
   "confidence": 69,
   "odds": 1.45,
   "score": "5–0",
   "status": "win"
  },
  {
   "date": "2026-09-13",
   "league": "BL1",
   "leagueName": "Bundesliga",
   "match": "RB Leipzig — HSV",
   "model": "elo",
   "tip": "Victoire RB Leipzig",
   "confidence": 66,
   "odds": 1.51,
   "score": "5–0",
   "status": "win"
  },
  {
   "date": "2026-09-14",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Real Betis",
   "model": "poisson",
   "tip": "Victoire Real Betis",
   "confidence": 39,
   "odds": 2.53,
   "score": "1–2",
   "status": "win"
  },
  {
   "date": "2026-09-14",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Villarreal — Real Betis",
   "model": "elo",
   "tip": "Victoire Villarreal",
   "confidence": 35,
   "odds": 2.86,
   "score": "1–2",
   "status": "loss"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Rayo Vallecano — Espanyol",
   "model": "poisson",
   "tip": "Victoire Espanyol",
   "confidence": 69,
   "odds": 1.45,
   "score": "2–1",
   "status": "loss"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Rayo Vallecano — Espanyol",
   "model": "elo",
   "tip": "Victoire Rayo Vallecano",
   "confidence": 37,
   "odds": 2.68,
   "score": "2–1",
   "status": "win"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Alavés — Valencia",
   "model": "poisson",
   "tip": "Victoire Alavés",
   "confidence": 95,
   "odds": 1.06,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Alavés — Valencia",
   "model": "elo",
   "tip": "Victoire Alavés",
   "confidence": 60,
   "odds": 1.66,
   "score": "0–1",
   "status": "loss"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Elche — Real Madrid",
   "model": "poisson",
   "tip": "Victoire Real Madrid",
   "confidence": 93,
   "odds": 1.07,
   "score": "2–3",
   "status": "win"
  },
  {
   "date": "2026-09-15",
   "league": "PD",
   "leagueName": "Liga",
   "match": "Elche — Real Madrid",
   "model": "elo",
   "tip": "Victoire Real Madrid",
   "confidence": 43,
   "odds": 2.31,
   "score": "2–3",
   "status": "win"
  }
 ]
};
